### ISSUE TITLE
Create landing page banner

### ISSUE THREAD

**Issue by ogranada** [carlosrojaso/vueweek#6]
As a user, I want to have a banner with information and a call to action button, so that allows me to access to Livestream web page created for the Vue-Week.

**Comment by carlosrojaso** [comment]
this banner is on top of the view or in the middle?

**Comment by ogranada** [comment]
According to previous projects (included in the Readme file) should be on top of the page.

**Comment by carlosrojaso** [comment]
got it.

Un Abrazo / Kind Regards / Atenciosamente,

Ing. Carlos A. Rojas.
@carlosrojas_o

ᐧ

**Comment by ogranada** [comment]
Could you check the [PR](https://github.com/carlosrojaso/vueweek/pull/7)?

Thanks :D

**Comment by carlosrojaso** [comment]
i did
Un Abrazo / Kind Regards / Atenciosamente,

Ing. Carlos A. Rojas.
@carlosrojas_o

ᐧ

**Comment by ogranada** [comment]
Fixed by [PR-7](https://github.com/carlosrojaso/vueweek/pull/7) and [PR-8](https://github.com/carlosrojaso/vueweek/pull/8)
